In [1]:
import numpy as np 
import MDAnalysis as md

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
POS = md.Universe('WaterBox.pdb')

/opt/anaconda3/lib/python3.9/site-packages/MDAnalysis/topology/PDBParser.py:331: UserWarning: Element information is missing, elements attribute will not be populated. If needed these can be guessed using MDAnalysis.topology.guessers.
  warnings.warn("Element information is missing, elements attribute "


In [5]:
POS.atoms.positions

array([[ 7.202, -0.549, 10.503],
       [ 7.541, -0.426, 11.436],
       [ 7.565,  0.178,  9.92 ],
       ...,
       [ 8.134, -5.881, -4.124],
       [ 8.484, -6.663, -4.638],
       [ 8.187, -6.076, -3.144]], dtype=float32)

In [6]:
dtype=[
    ('record','U6'),
    ('atom_id','i4'),
    ('atom_name','U4'),
    ('res_name','U4'),
    ('res_id','i4'),
    ('x','f8'),
    ('y','f8'),
    ('z','f8'),
    ('occupancy','f8'),
    ('temp_factor','f8'),
    ('segment','U6')
]

In [7]:
data = np.genfromtxt(
    open('WaterBox.pdb','r'),
    dtype=dtype,
    autostrip=True
)

In [8]:
data

array([('ATOM',    1, 'OH2', 'SPCE',   1, 7.202, -0.549, 10.503, 0., 0., 'SOLV'),
       ('ATOM',    2, 'H1', 'SPCE',   1, 7.541, -0.426, 11.436, 0., 0., 'SOLV'),
       ('ATOM',    3, 'H2', 'SPCE',   1, 7.565,  0.178,  9.92 , 0., 0., 'SOLV'),
       ...,
       ('ATOM', 1534, 'OH2', 'SPCE', 512, 8.134, -5.881, -4.124, 0., 0., 'SOLV'),
       ('ATOM', 1535, 'H1', 'SPCE', 512, 8.484, -6.663, -4.638, 0., 0., 'SOLV'),
       ('ATOM', 1536, 'H2', 'SPCE', 512, 8.187, -6.076, -3.144, 0., 0., 'SOLV')],
      dtype=[('record', '<U6'), ('atom_id', '<i4'), ('atom_name', '<U4'), ('res_name', '<U4'), ('res_id', '<i4'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8'), ('occupancy', '<f8'), ('temp_factor', '<f8'), ('segment', '<U6')])

In [11]:
data['x'], data['y'],data['z']

(array([7.202, 7.541, 7.565, ..., 8.134, 8.484, 8.187]),
 array([-0.549, -0.426,  0.178, ..., -5.881, -6.663, -6.076]),
 array([10.503, 11.436,  9.92 , ..., -4.124, -4.638, -3.144]))

In [15]:
oxygens = data[ data['atom_name']=="OH2" ]

In [17]:
oxygens['x']

array([ 7.2020e+00, -1.1530e+01,  1.1978e+01,  8.6550e+00,  1.0640e+01,
       -2.7940e+00, -8.6050e+00, -4.7610e+00, -1.1259e+01,  2.3540e+00,
       -7.3040e+00, -1.1819e+01,  8.0430e+00,  3.5950e+00,  1.3460e+00,
        3.5810e+00, -1.1397e+01,  8.4860e+00,  1.2497e+01, -1.2587e+01,
       -6.1960e+00,  5.7140e+00,  2.3290e+00, -1.2146e+01, -3.4400e-01,
        5.8650e+00, -1.2181e+01,  1.8300e-01,  1.2920e+01, -1.6200e+00,
       -2.4830e+00, -1.8930e+00, -8.7770e+00, -6.1850e+00,  5.4000e+00,
        3.2490e+00, -8.9190e+00,  1.1321e+01, -1.0850e+01,  1.0719e+01,
        6.2800e-01, -1.0915e+01,  5.0230e+00,  1.1478e+01,  9.9410e+00,
        7.8640e+00, -9.1200e+00,  7.8800e+00, -8.0680e+00, -6.9240e+00,
        1.0358e+01, -2.9780e+00, -9.3260e+00, -1.2430e+01, -5.4730e+00,
       -1.0634e+01, -5.7230e+00,  8.0230e+00, -1.2283e+01, -1.1819e+01,
       -8.6410e+00,  1.2241e+01, -3.0100e-01, -5.9190e+00, -8.5370e+00,
       -5.7800e+00,  4.0450e+00,  1.1250e+00,  6.7820e+00,  6.34