In [21]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\ssk\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [22]:
import numpy as np
import MDAnalysis as md
import pandas as pd
from io import StringIO

In [4]:
POS = md.Universe('WaterBox.pdb')

C:\Users\ssk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\MDAnalysis\topology\PDBParser.py:350: UserWarning: Element information is missing, elements attribute will not be populated. If needed these can be guessed using universe.guess_TopologyAttrs(context='default', to_guess=['elements']).
  warnings.warn("Element information is missing, elements attribute "


In [23]:

colspecs = [(0,6), (6,11), (12,16), (17,20), (21,22), (22,26), (30,38), (38,46), (46,54)]
column_names = ['record', 'atom_number', 'atom_name', 'residue_name', 'chain_id', 'residue_number', 'x', 'y', 'z']

with open("WaterBox.pdb") as file:
    lines = [line for line in file if line.startswith(("ATOM", "HETATM"))]

from io import StringIO
data_string = StringIO("".join(lines))

data = pd.read_fwf(data_string, colspecs=colspecs, names=column_names)

oxygen = data[data['atom_name'].str.strip() == 'OH2']


In [24]:
print(oxygen.head())
print(oxygen[['atom_name', 'x', 'y', 'z']])

   record  atom_number atom_name residue_name  chain_id  residue_number  \
0    ATOM            1       OH2          SPC       NaN               1   
3    ATOM            4       OH2          SPC       NaN               2   
6    ATOM            7       OH2          SPC       NaN               3   
9    ATOM           10       OH2          SPC       NaN               4   
12   ATOM           13       OH2          SPC       NaN               5   

         x       y       z  
0    7.202  -0.549  10.503  
3  -11.530 -10.058 -12.176  
6   11.978  -0.964   2.591  
9    8.655   9.863 -10.434  
12  10.640  11.630   4.200  
     atom_name       x       y       z
0          OH2   7.202  -0.549  10.503
3          OH2 -11.530 -10.058 -12.176
6          OH2  11.978  -0.964   2.591
9          OH2   8.655   9.863 -10.434
12         OH2  10.640  11.630   4.200
...        ...     ...     ...     ...
1521       OH2 -11.062  -7.419   6.898
1524       OH2 -14.467  10.823  -1.110
1527       OH2  -4.104  

In [25]:
POS.atoms.positions

array([[ 7.202, -0.549, 10.503],
       [ 7.541, -0.426, 11.436],
       [ 7.565,  0.178,  9.92 ],
       ...,
       [ 8.134, -5.881, -4.124],
       [ 8.484, -6.663, -4.638],
       [ 8.187, -6.076, -3.144]], shape=(1536, 3), dtype=float32)

In [27]:

('record','U6'),
('atom_id','i4'),
('atom_name','U4'),
('res_name','U4'),
('res_id','i4'),
('x','f8'),
('y','f8'),
('z','f8'),
('occupancy','f8'),
('temp_factor','f8'),
('segment','U6')

('segment', 'U6')

In [28]:
dtype=[
    ('record','U6'),
    ('atom_id','i4'),
    ('atom_name','U4'),
    ('res_name','U4'),
    ('res_id','i4'),
    ('x','f8'),
    ('y','f8'),
    ('z','f8'),
    ('occupancy','f8'),
    ('temp_factor','f8'),
    ('segment','U6')
]

In [29]:
data = np.genfromtxt(
    open('WaterBox.pdb','r'),
    dtype=dtype,
    autostrip=True
)

In [30]:
print (data)

[('ATOM',    1, 'OH2', 'SPCE',   1, 7.202, -0.549, 10.503, 0., 0., 'SOLV')
 ('ATOM',    2, 'H1', 'SPCE',   1, 7.541, -0.426, 11.436, 0., 0., 'SOLV')
 ('ATOM',    3, 'H2', 'SPCE',   1, 7.565,  0.178,  9.92 , 0., 0., 'SOLV')
 ...
 ('ATOM', 1534, 'OH2', 'SPCE', 512, 8.134, -5.881, -4.124, 0., 0., 'SOLV')
 ('ATOM', 1535, 'H1', 'SPCE', 512, 8.484, -6.663, -4.638, 0., 0., 'SOLV')
 ('ATOM', 1536, 'H2', 'SPCE', 512, 8.187, -6.076, -3.144, 0., 0., 'SOLV')]


In [31]:
data['x'], data['y'], data['z']

(array([7.202, 7.541, 7.565, ..., 8.134, 8.484, 8.187], shape=(1536,)),
 array([-0.549, -0.426,  0.178, ..., -5.881, -6.663, -6.076], shape=(1536,)),
 array([10.503, 11.436,  9.92 , ..., -4.124, -4.638, -3.144], shape=(1536,)))

In [32]:
np.ndarray 

numpy.ndarray

In [34]:
data = pd.read_csv("WaterBox.pdb")

In [35]:
oxygen['x']

0        7.202
3      -11.530
6       11.978
9        8.655
12      10.640
         ...  
1521   -11.062
1524   -14.467
1527    -4.104
1530    -1.794
1533     8.134
Name: x, Length: 512, dtype: float64

In [36]:
arr = np.array([oxygen['x']])
min_val = np.min(arr)
max_val = np.max(arr)

In [37]:
print(min_val)

-14.467


In [38]:
print(max_val)

13.532


In [40]:
O2H=oxygen['x']

In [42]:
x= O2H

In [43]:
x

0        7.202
3      -11.530
6       11.978
9        8.655
12      10.640
         ...  
1521   -11.062
1524   -14.467
1527    -4.104
1530    -1.794
1533     8.134
Name: x, Length: 512, dtype: float64

In [63]:
binwidth = 1.0
int(x[0]/binwidth)

7

In [70]:
for i in range(int(max_val)):
    print(i, x.iloc[i], 1 + int(x.iloc[i] / binwidth))

0 7.202 8
1 -11.53 -10
2 11.978 12
3 8.655 9
4 10.64 11
5 -2.794 -1
6 -8.605 -7
7 -4.761 -3
8 -11.259 -10
9 2.354 3
10 -7.304 -6
11 -11.819 -10
12 8.043 9


In [72]:
x = oxygen['x'].values      
binwidth = 1.0
max_val = x.max()

for i in range(len(x)):     
    bin_number = 1 + int(x[i] / binwidth)
    print(i, x[i], f"→ bin {bin_number}")

0 7.202 → bin 8
1 -11.53 → bin -10
2 11.978 → bin 12
3 8.655 → bin 9
4 10.64 → bin 11
5 -2.794 → bin -1
6 -8.605 → bin -7
7 -4.761 → bin -3
8 -11.259 → bin -10
9 2.354 → bin 3
10 -7.304 → bin -6
11 -11.819 → bin -10
12 8.043 → bin 9
13 3.595 → bin 4
14 1.346 → bin 2
15 3.581 → bin 4
16 -11.397 → bin -10
17 8.486 → bin 9
18 12.497 → bin 13
19 -12.587 → bin -11
20 -6.196 → bin -5
21 5.714 → bin 6
22 2.329 → bin 3
23 -12.146 → bin -11
24 -0.344 → bin 1
25 5.865 → bin 6
26 -12.181 → bin -11
27 0.183 → bin 1
28 12.92 → bin 13
29 -1.62 → bin 0
30 -2.483 → bin -1
31 -1.893 → bin 0
32 -8.777 → bin -7
33 -6.185 → bin -5
34 5.4 → bin 6
35 3.249 → bin 4
36 -8.919 → bin -7
37 11.321 → bin 12
38 -10.85 → bin -9
39 10.719 → bin 11
40 0.628 → bin 1
41 -10.915 → bin -9
42 5.023 → bin 6
43 11.478 → bin 12
44 9.941 → bin 10
45 7.864 → bin 8
46 -9.12 → bin -8
47 7.88 → bin 8
48 -8.068 → bin -7
49 -6.924 → bin -5
50 10.358 → bin 11
51 -2.978 → bin -1
52 -9.326 → bin -8
53 -12.43 → bin -11
54 -5.473 → bin 

In [73]:
binwidth = 1.0
bins = np.arange(oxygen['x'].min(), oxygen['x'].max() + binwidth, binwidth)

In [74]:
oxygen['x_bin'] = pd.cut(oxygen['x'], bins)

In [75]:
bin_counts = oxygen['x_bin'].value_counts().sort_index()

In [76]:
for bin_range, count in bin_counts.items():
    print(f"{bin_range} → {count} atoms")

(-14.467, -13.467] → 1 atoms
(-13.467, -12.467] → 4 atoms
(-12.467, -11.467] → 18 atoms
(-11.467, -10.467] → 27 atoms
(-10.467, -9.467] → 17 atoms
(-9.467, -8.467] → 28 atoms
(-8.467, -7.467] → 15 atoms
(-7.467, -6.467] → 23 atoms
(-6.467, -5.467] → 18 atoms
(-5.467, -4.467] → 15 atoms
(-4.467, -3.467] → 25 atoms
(-3.467, -2.467] → 17 atoms
(-2.467, -1.467] → 23 atoms
(-1.467, -0.467] → 16 atoms
(-0.467, 0.533] → 16 atoms
(0.533, 1.533] → 21 atoms
(1.533, 2.533] → 17 atoms
(2.533, 3.533] → 18 atoms
(3.533, 4.533] → 17 atoms
(4.533, 5.533] → 25 atoms
(5.533, 6.533] → 22 atoms
(6.533, 7.533] → 16 atoms
(7.533, 8.533] → 26 atoms
(8.533, 9.533] → 20 atoms
(9.533, 10.533] → 21 atoms
(10.533, 11.533] → 23 atoms
(11.533, 12.533] → 17 atoms
(12.533, 13.533] → 5 atoms
